[build]
  # The command that Netlify will use to build the site
  command = "npm run build"
  
  # The directory where the build output will be stored
  publish = ".next"

  # Set environment variables if necessary
  environment = { NODE_ENV = "production" }

[[plugins]]
  package = "@netlify/plugin-nextjs"
